options:
  prometheus-node-exporter-image-path:
    type: string
    description: |
      The location of the image to use,
      e.g. "registry.example.com/prometheus:v1".

      This setting is required.
    default: "prom/node-exporter:latest"
  prometheus-node-exporter-image-username:
    type: string
    description: |
      The username for accessing the registry specified in
      prometheus-image-path.
    default: ""
  prometheus-node-exporter-image-password:
    type: string
    description: |
      The password associated with prometheus-image-username for
      accessing the registry specified in prometheus-image-path.
    default: ""
  port:
    description: The port prometheus will be listening on
    type: int
    default: 9100
