name: node-exporter
summary: Prometheus node exporter for Kubernetes clusters
maintainers:
    - David García <david.garcia@canonical.com>
description: |
    Prometheus exporter for hardware and OS metrics exposed by
    *NIX kernels, written in Go with pluggable metric collectors.
tags:
    - observability
    - lma
    - prometheus
    - monitoring
    - alerting
    - grafana
series:
    - kubernetes
provides:
    prometheus-target:
        interface: http
deployment:
    type: stateful
